void make_table_hnumber(double ** ,int,int,int);
void make_table_hvector(vector <double> **, int, int, int);
void print_table_hnumber(double ** , int ,int);
void print_table_hvector(vector <double> **, int, int, int);
void print_hashtable(HashTable *);
double find_radius(string line);
double	vectors_distance(string,vector<double> ,vector<double>);
double euclidean_distance(vector<double>,vector<double>);
double cosine_distance(vector<double>, vector <double>);
set <DataVector *> rangesearch(int,int,HashTable *, double,DataVector *,string);
set <DataVector *> cube_rangesearch(int,int,int,int,list < DataVector *> *,double,DataVector *,string);
map <DataVector *, double> approximateNN( int,int,HashTable * ,DataVector *,string);
map <DataVector *, double> cube_approximateNN(int,int,int,int,list < DataVector *> *,DataVector *,string);
map <DataVector *, double> trueNN(vector <DataVector *>, DataVector *,string);
int find_dimension(string);
string find_metric(string);
int hamming_distance(int,int);
int bitstring_to_int(string);
